---
- name: Pre-flight checks
  tags:
    - checks
    - pre-flight
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/pre-flight/main.yml"

- name: Install BOINC
  tags:
    - installation
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/installation.yml"

- name: Configure BOINC
  tags:
    - configuration
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/configuration/main.yml"

- name: Configure BOINC's group privileges
  when: boinc_set_files_group_writable
  tags:
    - group_privileges
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/group_privileges.yml"

- name: Give the user membership to BOINC's group
  when: boinc_add_user_to_the_boinc_group
  tags:
    - group_membership
  notify: Restart BOINC's service
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: boinc
    append: true

- name: Attach the client to the Account Manager
  tags:
    - account_manager
    - acct_mgr
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/acct_mgr.yml"
