---
- name: Install BOINC
  import_tasks: "{{ role_path }}/tasks/installation.yml"
  tags:
    - installation

- name: Configure BOINC
  import_tasks: "{{ role_path }}/tasks/configuration/main.yml"
  tags:
    - configuration

- name: Configure BOINC's group privileges
  import_tasks: "{{ role_path }}/tasks/group-privileges.yml"

- name: Give the user membership to BOINC's group
  when: boinc_add_user_to_the_boinc_group
  tags:
    - group_membership
  notify: Restart BOINC's service
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: boinc
    append: true
