---
- name: Set the password for GUI authentication
  tags:
    - gui_rpc_auth
  notify: Restart BOINC's service
  become: true
  lineinfile:
    path: "{{ boinc_config_dir }}/gui_rpc_auth.cfg"
    regexp: .*
    line: "{{ boinc_gui_rpc_auth_password }}"
    create: true
    owner: boinc
    group: boinc
    mode: "{{ boinc_set_files_group_writable | ternary('ug=rw', 'u=rw,g=r') }}"

- name: Configure remote management of the BOINC client
  import_tasks: "{{ role_path }}/tasks/configuration/remote_gui_rpc.yml"
  tags:
    - remote_gui_rpc
